### ISSUE TITLE
此翻译项目已停止？

### ISSUE THREAD

**Issue by potterhere** [jeasonstudio/CN-VScode-Docs#76]
翻译工作是否仍在继续进行，感觉已经停滞了？想着翻译其中的一部分。

**Comment by bluexp** [comment]
好像是停滞中，vscode版本一一直在更新，所以这个项目要保持持续还是很难的。

**Comment by jeasonstudio** [comment]
> 好像是停滞中，vscode版本一一直在更新，所以这个项目要保持持续还是很难的。

@potterhere 是的，vsc 目前迭代太快，而且经常有 break 的更新，所以目前这个项目没有继续跟进。
