### ISSUE TITLE
关于 Getting Started with Python in VS Code 章节的翻译计划

### ISSUE THREAD

**Issue by coderxdotwang** [jeasonstudio/CN-VScode-Docs#77]
似乎有段时间没有更新了，不知道是否有人认领了 Getting Started with Python in VS Code 章节，我正开始在本地翻译（完成后提交），如果有人已经做了这个工作，at我一下，谢谢。

**Comment by jeasonstudio** [comment]
@CoderWangxx 不建议再跟进这个 repo，已经和官方的文档项目差距比较大。如果你有兴趣可以单独翻译：[Python in Visual Studio Code](https://code.visualstudio.com/docs/languages/python) 这篇文章。
Btw，如果你有兴趣，可以投稿到我的知乎专栏：https://zhuanlan.zhihu.com/Jeason

祝好。

**Comment by CoderWangxx** [comment]
Python in Visual Studio Code 这篇似乎已有[翻译文档](https://jeasonstudio.gitbooks.io/vscode-cn-doc/content/md/语言/python.html)，我在翻译Python的详细文档[Getting Started with Python in VS Code](https://code.visualstudio.com/docs/python/python-tutorial) - 在 VS Code 中开始使用Python，完成后逐节释出：）

**Comment by b0t9527** [comment]
这段时间有(~~比~~)点(~~较~~)忙(~~懒~~)，初步翻译完 Python 中的[第一小节](https://github.com/b0t9527/CN-VScode-Docs/blob/python-tutorial/md/Python/在%20VS%20Code%20中开始使用%20Python.md)，有空帮忙校对一下？看下是否符合规范或需要完善 ：)
@jeasonstudio

**Comment by jeasonstudio** [comment]
> 这段时间有(比)点(较)忙(懒)，初步翻译完 Python 中的[第一小节](https://github.com/b0t9527/CN-VScode-Docs/blob/python-tutorial/md/Python/%E5%9C%A8%20VS%20Code%20%E4%B8%AD%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8%20Python.md)，有空帮忙校对一下？看下是否符合规范或需要完善 ：)
> @jeasonstudio

PR welcome.

**Comment by b0t9527** [comment]
done!🍻
接下来计划先翻译[Django Tutorial in Visual Studio Code](https://code.visualstudio.com/docs/python/tutorial-django)，然后再回过头来翻译 Editing Code、Linting、Debugging等（听起来似乎是很久以后的事情：）。

**Comment by coderxdotwang** [comment]
bug 解不完 😅
